# Generated by Django 5.0.5 on 2024-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_todo_poc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poc',
            old_name='updated',
            new_name='currentTime',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='user',
        ),
    ]
