# Generated by Django 5.0.5 on 2024-05-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_updated_poc_currenttime_remove_poc_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poc',
            name='task',
        ),
    ]
