# Generated by Django 5.0.5 on 2024-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_poc_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='poc',
            name='currentTime',
            field=models.CharField(default=b'2024-05-16T12:24:48\n', max_length=180),
        ),
    ]
