# Generated by Django 5.0.5 on 2024-05-16 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_poc_name_alter_poc_currenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='currentTime',
            field=models.CharField(default=datetime.datetime(1970, 1, 1, 0, 0), max_length=180),
        ),
    ]
